spring.application.name=gateway-service
server.port=${GATEWAY_PORT}
server.forward-headers-strategy=framework

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=evenements-websocket
spring.cloud.gateway.routes[0].uri=lb:ws://evenements-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/evenements/notifications/stream

spring.cloud.gateway.routes[1].id=sociale-websocket
spring.cloud.gateway.routes[1].uri=lb:ws://sociale-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/sociale/ws

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[3].id=annonces-service
spring.cloud.gateway.routes[3].uri=lb://annonces-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/annonces/**, /api/commentaires/**

spring.cloud.gateway.routes[4].id=evenements-service
spring.cloud.gateway.routes[4].uri=lb://evenements-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/evenements/**

spring.cloud.gateway.routes[5].id=sociale-service
spring.cloud.gateway.routes[5].uri=lb://sociale-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/sociale/**

# CORS
app.cors.allowed-origins=${GATEWAY_ALLOWED_ORIGINS}

# Deduplicate CORS Headers to prevent duplicate 'Access-Control-Allow-Origin' errors
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
