spring.application.name=discovery-service
server.port=${DISCOVERY_PORT}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
eureka.instance.hostname=${EUREKA_HOSTNAME}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus