spring.application.name=sociale-service
server.port=${SOCIALE_PORT}

# Database
spring.datasource.url=${SOCIALE_DB_URL}
spring.datasource.username=${SOCIALE_DB_USERNAME}
spring.datasource.password=${SOCIALE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=ERROR

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus

# Security
security.jwt.secret=${JWT_SECRET}

# Presence Config
sociale.presence.timeout=${SOCIALE_PRESENCE_TIMEOUT}

# WebSocket Config
app.websocket.user-id-attribute=${SOCIALE_WS_USER_ID_ATTR}
app.websocket.token-param=${SOCIALE_WS_TOKEN_PARAM}
